Updates

diff --git a/BAN-WORK-TOP/Scripts/application/pack-shared b/BAN-WORK-TOP/Scripts/application/pack-shared
--- a/BAN-WORK-TOP/Scripts/application/pack-shared
+++ b/BAN-WORK-TOP/Scripts/application/pack-shared
@@ -1,39 +1,32 @@
 #!/bin/bash
 #
-# Pack shared and copy nuspec file to Local Packages
+# With .NET 5 we build our packages automatically and can just copy them from the output folder to the shared package cache
 #
-# Required env variables: 
-#   grid_repository_dir - absolute path to directory of the grid repository
-#   shared_repository_dir - absolute path to directory of the shared repository
-#
-# Required scripts: 
-#   nuget-pack
-#   clear-shared-cache
-#
-# Optional scripts: 
-#   shared - for pre-building
+
 
 say() {
-	echo "$@" 1>&2 # redirect stdout to stderr
+  echo "$@" 1>&2 # redirect stdout to stderr
 }
 
 die() {
-	say "$2"
-	exit "$1"
+  say "$2"
+  exit "$1"
 }
 
 function echo_help() {
-	echo "Pack nuget shared."
+  echo "Copy nuget packages from shared repo to local package cache."
     echo " "
     echo "actions:"
-    echo "-h, --help        					          show brief help"
-    echo "-s, --set-config       set Grid 3 directory build props to 1.0.0.0"
-    echo "-b, --build       					          build solution before packing"
+    echo "-h, --help             show brief help"
+    echo "-s, --set-config       set directory build props in both shared and Grid to ${DEFAULT_PACKAGE_VERSION}. Should use in combination with build"
+    echo "-b, --build            Build the shared solution"
     die 0
 }
 
-DEFAULT_PACKAGE_VERSION=1.0.0.0 # In the case that the version of the package cannot be found from the assembly file, this is the default we'll use.
-SET_GRID_CONFIG=false
+
+DEFAULT_PACKAGE_VERSION=2.0.0
+SET_CONFIG=false
+VERSION_REGEX='[0-9]\.[0-9]\.[0-9]'
 BUILD_BEFORE_PACKING=false
 
 while test $# -gt 0; do
@@ -42,61 +35,69 @@ while test $# -gt 0; do
       echo_help
       ;;
     -s|--set-config)
-      SET_GRID_CONFIG=true
+      SET_CONFIG=true
       shift
       ;;
     -b|--build)
       BUILD_BEFORE_PACKING=true
       shift
       ;;
-  	-sb|-bs)
-      SET_GRID_CONFIG=true
+    -sb|-bs)
+      SET_CONFIG=true
       BUILD_BEFORE_PACKING=true
       shift
       ;;
     *)
-	  shift
+    shift
       continue
       ;;
   esac
 done
 
-if $BUILD_BEFORE_PACKING; then
-	shared -b || exit 1
+if $SET_CONFIG; then
+  # Package version must be higher than the current version for Grids dependencies. For example, Grid depends on Eyegaze which depends on shared (as of 06/04/2022 this is roughly version 2.0.40.
+  # The version we choose needs to be higher than these dependencies.
+  DEFAULT_PACKAGE_VERSION=5.5.5
+
+  say "
+  -- Setting Shared Directory.Build.Props Version --
+  "
+  SHARED_DIRECTORY_BUILD_PROPS="${shared_repository_dir}/Source/Directory.Build.props"
+  sed --in-place s_"Version>${VERSION_REGEX}\+"_"Version>${DEFAULT_PACKAGE_VERSION}"_g ${SHARED_DIRECTORY_BUILD_PROPS}
+  
+  say "Show Shared Version now in Directory.Build.props:"
+  grep -oP "Version>${VERSION_REGEX}+" "${SHARED_DIRECTORY_BUILD_PROPS}"
+  
 fi
 
+if $BUILD_BEFORE_PACKING; then
+  shared -b || die 1 "Build failed"
+fi
 
-echo " 
--- Creating packages --
+say "
+-- Copying packages from output directory to local package store --
 "
-SHARED_PROJ_PATH="${shared_repository_dir}/Source/SensorySoftware.Shared/SensorySoftware.Shared.csproj"
-METAFILE_NUSPEC_PATH="${shared_repository_dir}/Source/SensorySoftware.Symbols.MetafileReader.Desktop/SensorySoftware.Symbols.MetafileReader.Desktop.csproj"
-SHARED_DESKTOP_PROJ_PATH="${shared_repository_dir}/Source/SensorySoftware.Shared.Desktop/SensorySoftware.Shared.Desktop.csproj"
-SHARED_FLUENTUI_PROJ_PATH="${shared_repository_dir}/Source/SensorySoftware.Shared.FluentUI/SensorySoftware.Shared.FluentUI.csproj"
 
-nuget-pack $SHARED_PROJ_PATH $SHARED_DESKTOP_PROJ_PATH $SHARED_FLUENTUI_PROJ_PATH $SHARED_IOS_PROJ_PATH $METAFILE_NUSPEC_PATH
+cp -v "${shared_repository_dir}/Source/SensorySoftware.Shared/bin/Debug/SensorySoftware.Shared.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}"
+cp -v "${shared_repository_dir}/Source/SensorySoftware.Symbols.MetafileReader.Desktop/bin/Debug/SensorySoftware.Symbols.MetafileReader.Desktop.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}"
+cp -v "${shared_repository_dir}/Source/SensorySoftware.Shared.Desktop/bin/Debug/SensorySoftware.Shared.Desktop.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}"
+cp -v "${shared_repository_dir}/Source/SensorySoftware.Shared.FluentUI/bin/Debug/SensorySoftware.Shared.FluentUI.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}"
+cp -v "${shared_repository_dir}/Source/SensorySoftware.Shared.HardwareLicensingServiceClient/bin/Debug/SensorySoftware.Shared.HardwareLicensingServiceClient.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}"
 
-echo " 
--- Removing cached packages --
+say "
+-- Removing cached packages from global nuget cache --
 "
+
 clear-shared-cache
 
-if $SET_GRID_CONFIG; then
-	echo "
-	-- Setting Directory.Build.Props SharedVersion --
-	"
-	ASSEMBLY_INFO_DIR="${shared_repository_dir}/Source/SensorySoftware.shared/Properties/AssemblyInfo.cs"
-	PACKAGE_VERSION=$(grep -oP 'AssemblyFileVersion\(\"\K([0-9]\.[0-9]\.[0-9]\.[0-9])' "${ASSEMBLY_INFO_DIR}")
- 	test "$PACKAGE_VERSION" == "" && PACKAGE_VERSION="${DEFAULT_PACKAGE_VERSION}" && echo "No package version obtained from ${ASSEMBLY_INFO_DIR}"
- 	echo "Setting package version to ${PACKAGE_VERSION}"
-	
-	# sed for the old props format: if it can't find it, it won't change anything
-	sed --in-place s_"SharedVersion>1\.[0-1]\.[0-9]\.[0-9][0-9][0-9]"_"SharedVersion>${PACKAGE_VERSION}"_g ${grid_repository_dir}/Source/Directory.Build.props
-	
-	# sed for the new range props format: if it can't find it, it won't change anything
-	sed --in-place s_"SharedVersion>\[1\.[0-1]\.[0-9]\.[0-9][0-9][0-9]"_"SharedVersion>\[${PACKAGE_VERSION}"_g ${grid_repository_dir}/Source/Directory.Build.props
-	
-  echo "Show SharedVersion now in Directory.Build.props:"
-  grep SharedVersion ${grid_repository_dir}/Source/Directory.Build.props
+if $SET_CONFIG; then
+  say "
+  -- Setting Grid Directory.Build.Props SharedVersion --
+  "
+  GRID_DIRECTORY_BUILD_PROPS="${grid_repository_dir}/Source/Directory.Build.props"
+  sed --in-place s_"SharedVersion>${VERSION_REGEX}\+"_"SharedVersion>${DEFAULT_PACKAGE_VERSION}"_g ${GRID_DIRECTORY_BUILD_PROPS}
+  
+  
+  say "Show Grid SharedVersion now in Directory.Build.props:"
+  grep -oP "SharedVersion>${VERSION_REGEX}+" "${GRID_DIRECTORY_BUILD_PROPS}"
 fi
-
