Update

diff --git a/BAN-WORK-TOP/Scripts/git-tag-release b/BAN-WORK-TOP/Scripts/git-tag-release
--- a/BAN-WORK-TOP/Scripts/git-tag-release
+++ b/BAN-WORK-TOP/Scripts/git-tag-release
@@ -1,11 +1,17 @@
 #!/bin/bash
 #
 # Script to tag the next version of a release
+# For tagging of grid or gridresources repositories only
 #
 
+NC='\033[0m'              # Text Reset
+Green='\033[0;32m'
+Yellow='\033[0;33m'
+Blue='\033[0;34m'
+Red='\033[0;31m'
 
 function say() {
-  echo "$@" >&2
+  echo -e "$@" >&2
 }
 
 function die() {
@@ -14,11 +20,11 @@ function die() {
 }
 
 function echo_help() {
-  echo "Tag release"
+  echo "Tag release of grid or gridresources repositories"
   echo ""
     echo " "
-    echo "actions:"
-    echo "-h, --help        show brief help"
+    echo "${Yellow}actions:"
+    echo "${Yellow}-h, --help        show brief help"
     die 0
 }
 
@@ -27,10 +33,6 @@ while test $# -gt 0; do
     -h|--help)
       echo_help
       ;;
-    -p|--pretty)
-    PRETTY=true;
-    shift
-      ;;
     *)
     shift
       continue
@@ -38,12 +40,17 @@ while test $# -gt 0; do
   esac
 done
 
+# Test you are in a supported repo
+REPO_NAME=$(basename -s .git `git config --get remote.origin.url`)
+test $REPO_NAME != "gridresources" && test $REPO_NAME != "grid" && die 1 "${Red}Repository name ${NC}\"$REPO_NAME\" ${Red}is not gridresources or grid. Tagging pattern may not be valid"
+
+
 PREVIOUS_TAG=$(git describe --tags --abbrev=0)
-echo "==============================================" 
-echo "Tagging util for Grid and Content repositories"
-echo "The previous tag is $PREVIOUS_TAG" 
-echo "===============================================" 
-echo "" 
+say "${Blue}==============================================" 
+say "${NC}Tagging util for Grid and Content repositories"
+say "${NC}The previous tag is $PREVIOUS_TAG" 
+say "${Blue}==============================================" 
+say "" 
 
 TAG_STRING=$(echo $PREVIOUS_TAG | tr "." "\n" )
 TAG_ARRAY=($TAG_STRING)
@@ -53,34 +60,34 @@ TAG_ARRAY_LENGTH=${#TAG_ARRAY[@]}
 let "PATCH_INDEX=$TAG_ARRAY_LENGTH - 1"
 let "MINOR_VERSION_INDEX=$TAG_ARRAY_LENGTH - 2"
 
-# Assumes tag has the form Grid_3.0.MINOR_VERSION.BUILD_VERSION
+# Assumes tag has the form Grid_3.0.MINOR_VERSION.BUILD_VERSION or GridResources_1.MINOR_VERSION.BUILD_VERSION
 PATCH_VERSION=${TAG_ARRAY[$PATCH_INDEX]}
 MINOR_VERSION=${TAG_ARRAY[$MINOR_VERSION_INDEX]}
 
-let "PATCH_VERSION_INCREASE=$PATCH_VERSION + 1"
-let "MINOR_VERSION_INCREASE=$MINOR_VERSION + 1"
+let "PATCH_VERSION_NEXT=$PATCH_VERSION + 1"
+let "MINOR_VERSION_NEXT=$MINOR_VERSION + 1"
 
 # Construct a new tag for a minor version increase
 MINOR_VERSION_TAG_ARRAY=(${TAG_ARRAY[*]})
-MINOR_VERSION_TAG_ARRAY[$MINOR_VERSION_INDEX]=$MINOR_VERSION_INCREASE
+MINOR_VERSION_TAG_ARRAY[$MINOR_VERSION_INDEX]=$MINOR_VERSION_NEXT
 MINOR_VERSION_TAG_ARRAY[$PATCH_INDEX]=0
-TAG_MINOR_VERSION_INCREASE=$( IFS=$'.'; echo "${MINOR_VERSION_TAG_ARRAY[*]}" )
+TAG_MINOR_VERSION_NEXT=$( IFS=$'.'; echo "${MINOR_VERSION_TAG_ARRAY[*]}" )
 
 # Construct a new tag for a patch increase
 PATCH_VERSION_TAG_ARRAY=(${TAG_ARRAY[*]})
-PATCH_VERSION_TAG_ARRAY[$PATCH_INDEX]=$PATCH_VERSION_INCREASE
-TAG_PATCH_INCREASE=$( IFS=$'.'; echo "${PATCH_VERSION_TAG_ARRAY[*]}" )
+PATCH_VERSION_TAG_ARRAY[$PATCH_INDEX]=$PATCH_VERSION_NEXT
+TAG_PATCH_NEXT=$( IFS=$'.'; echo "${PATCH_VERSION_TAG_ARRAY[*]}" )
 
-echo "Do you wish to create a tag that increases:"
-echo "  1. The minor version from $MINOR_VERSION to $MINOR_VERSION_INCREASE -> $TAG_MINOR_VERSION_INCREASE"
-echo "  2. The patch version from $PATCH_VERSION to $PATCH_VERSION_INCREASE -> $TAG_PATCH_INCREASE"
+say "${Yellow}Do you wish to create a tag that increases:"
+say "  ${Yellow}1. The minor version from ${NC}$MINOR_VERSION${Yellow} to ${NC}$MINOR_VERSION_NEXT${Yellow} -> ${NC}$TAG_MINOR_VERSION_NEXT"
+say "  ${Yellow}2. The patch version from ${NC}$PATCH_VERSION${Yellow} to ${NC}$PATCH_VERSION_NEXT${Yellow} -> ${NC}$TAG_PATCH_NEXT"
 read SELECTED_NUMBER
 if [ $SELECTED_NUMBER -eq 1 ]; then
-  echo "Incrementing the minor version. Creating new tag called $TAG_MINOR_VERSION_INCREASE which follow $PREVIOUS_TAG."
-  git tag $TAG_MINOR_VERSION_INCREASE
+  say "${Green}Incrementing the minor version. Creating new tag called ${NC}$TAG_MINOR_VERSION_NEXT${Green} which follow ${NC}$PREVIOUS_TAG."
+  git tag $TAG_MINOR_VERSION_NEXT
 elif [ $SELECTED_NUMBER -eq 2 ]; then
-  echo "Incrementing the patch version. Creating new tag called $TAG_PATCH_INCREASE which follow $PREVIOUS_TAG."
-  git tag $TAG_PATCH_INCREASE
+  say "${Green}Incrementing the patch version. Creating new tag called ${NC}$TAG_PATCH_NEXT${Green} which follow ${NC}$PREVIOUS_TAG."
+  git tag $TAG_PATCH_NEXT
 else
-  echo "$SELECTED_NUMBER not 1 or 2. Aborting..."
+  die 1 "$SELECTED_NUMBER ${Red}not 1 or 2. Aborting..."
 fi
