Update packing scripts

diff --git a/BAN-WORK-TOP/Scripts/pack-shared b/BAN-WORK-TOP/Scripts/pack-shared
--- a/BAN-WORK-TOP/Scripts/pack-shared
+++ b/BAN-WORK-TOP/Scripts/pack-shared
@@ -16,9 +16,9 @@ function echo_help() {
 	echo "Pack nuget shared."
     echo " "
     echo "actions:"
-    echo "-h, --help        					show brief help"
+    echo "-h, --help        					          show brief help"
     echo "-s, --set-directory-build-props       set directory build props to 1.0.0.0"
-    echo "-b, --build       					build package before packing"
+    echo "-b, --build       					          build package before packing"
     die 0
 }
 
@@ -52,7 +52,8 @@ while test $# -gt 0; do
 done
 
 if $BUILD_BEFORE_PACKING; then
-	restore-and-build-shared || exit 0
+  # The below script will echo any errors in the case that it fails
+	restore-and-build-shared || exit 1
 fi
 
 
@@ -74,7 +75,7 @@ if $SET_DIRECTORY_BUILD_PROPS; then
 	echo "
 	-- Setting Directory.Build.Props SharedVersion --
 	"
-	ASSEMBLY_INFO_DIR="${shared_repository_dir}/Source/SensorySoftware.shared\Properties\AssemblyInfo.cs"
+	ASSEMBLY_INFO_DIR="${shared_repository_dir}/Source/SensorySoftware.shared/Properties/AssemblyInfo.cs"
 	PACKAGE_VERSION=$(grep -oP 'AssemblyFileVersion\(\"\K([0-9]\.[0-9]\.[0-9]\.[0-9])' "${ASSEMBLY_INFO_DIR}")
  	test "$PACKAGE_VERSION" == "" && PACKAGE_VERSION="${DEFAULT_PACKAGE_VERSION}" && echo "No package version obtained from ${ASSEMBLY_INFO_DIR}"
  	echo "Setting package version to ${PACKAGE_VERSION}"
