Update packing scripts

diff --git a/BAN-WORK-TOP/Scripts/application/build/eyegaze b/BAN-WORK-TOP/Scripts/application/build/eyegaze
--- a/BAN-WORK-TOP/Scripts/application/build/eyegaze
+++ b/BAN-WORK-TOP/Scripts/application/build/eyegaze
@@ -1,12 +1,9 @@
 #!/bin/bash
 #
-# For dot net framework and x86 builds of eyegaze
+# For dot net builds of eyegaze
 #
 # Required env variables: 
-#   eyegaze_repository_dir - absolute path to directory of the grid repository
-#
-# Required scripts
-#   msbuild32
+#   eyegaze_repository_dir - absolute path to directory of the eyegaze repository
 
 function say() {
 	echo "$@" >&2
@@ -24,56 +21,21 @@ function die() {
 
 function echo_help() {
 	echo "Eyegaze build script"
-  echo " "
-  echo "actions:"
-  echo "-c, --clean         clean directory with git clean -fdx -e \"*.vscode\"'"
-  echo "-r, --restore       restore nuget packages"
-  echo "-b, --build         build with msbuild"
-  echo "-d, --debug         run debug build"
+    echo " "
+    echo "options:"
+    echo "-c, --clean    clean the git repo before building"
   die 0
 }
 
 GIT_CLEAN=false
-RESTORE=false
-BUILD=false
-RUN_DEBUG=false
 
 while test $# -gt 0; do
   case "$1" in
   	-h|--help)
       echo_help
       ;;
-    -c|--clean)
+	-c|--clean)
       GIT_CLEAN=true
-      shift
-      ;;
-    -r|--restore)
-      RESTORE=true
-      shift
-      ;;
-    -b|--build)
-      BUILD=true
-      shift
-      ;;
-    -cr|-cr)
-      GIT_CLEAN=true
-      RESTORE=true
-      shift
-      ;;
-    -br|-br)
-      RESTORE=true
-      BUILD=true
-      shift
-      ;;
-    -bc|-cb)
-      GIT_CLEAN=true
-      BUILD=true
-      shift
-      ;;
-    -crb|-cbr|-brc|-bcr|-rbc|-rcb)
-      GIT_CLEAN=true
-      RESTORE=true
-      BUILD=true
       shift
       ;;
     *)
@@ -83,17 +45,14 @@ while test $# -gt 0; do
   esac
 done
 
-REPO_DIR=${eyegaze_repository_dir}
-SOLUTION_PATH="${REPO_DIR}/Source/SensorySoftware.Eyegaze.sln"
-
 if $GIT_CLEAN; then
 	title "Cleaning solution"
-	cd "${REPO_DIR}"
+	cd "${eyegaze_repository_dir}"
 	git clean -fxd  || die 1 "== git clean failed =="
 	cd -
 fi
 
-if $BUILD; then
-  title "Building solution"
-  dotnet build "${SOLUTION_PATH}" --configuration=Debug --verbosity=quiet || die 1  "== build failed =="
-fi
+SOLUTION_PATH="${eyegaze_repository_dir}/Source/SensorySoftware.Eyegaze.sln"
+
+title "Building solution"
+dotnet build "${SOLUTION_PATH}" --configuration Debug --verbosity quiet -consoleloggerparameters:ErrorsOnly || die 1  "== build failed =="
diff --git a/BAN-WORK-TOP/Scripts/application/build/shared b/BAN-WORK-TOP/Scripts/application/build/shared
--- a/BAN-WORK-TOP/Scripts/application/build/shared
+++ b/BAN-WORK-TOP/Scripts/application/build/shared
@@ -1,12 +1,9 @@
 #!/bin/bash
 #
-# For dot net framework and x86 cleaning, restoring and building of shared
+# For dot net building of shared desktop projects
 #
 # Required env variables: 
 #   shared_repository_dir - root directory of the shared repository
-#
-# Required scripts
-#   msbuild32
 
 function say() {
 	echo "$@" >&2
@@ -24,55 +21,21 @@ function die() {
 
 function echo_help() {
 	echo "Shared build script"
-  echo " "
-  echo "actions:"
-  echo "-c, --clean         clean directory with git clean -fdx"
-  echo "-r, --restore       restore nuget packages"
-  echo "-b, --build         build with msbuild"
+	echo " "
+    echo "options:"
+    echo "-c, --clean    clean the git repo before building"
   die 0
 }
 
 GIT_CLEAN=false
-RESTORE=false
-BUILD=false
-RUN_DEBUG=false
 
 while test $# -gt 0; do
   case "$1" in
   	-h|--help)
       echo_help
       ;;
-    -c|--clean)
+	-c|--clean)
       GIT_CLEAN=true
-      shift
-      ;;
-    -r|--restore)
-      RESTORE=true
-      shift
-      ;;
-    -b|--build)
-      BUILD=true
-      shift
-      ;;
-    -cr|-cr)
-      GIT_CLEAN=true
-      RESTORE=true
-      shift
-      ;;
-    -br|-br)
-      RESTORE=true
-      BUILD=true
-      shift
-      ;;
-    -bc|-cb)
-      GIT_CLEAN=true
-      BUILD=true
-      shift
-      ;;
-    -crb|-cbr|-brc|-bcr|-rbc|-rcb)
-      GIT_CLEAN=true
-      RESTORE=true
-      BUILD=true
       shift
       ;;
     *)
@@ -82,22 +45,33 @@ while test $# -gt 0; do
   esac
 done
 
-REPO_DIR=${shared_repository_dir}
-SOLUTION_PATH="${REPO_DIR}/Source/SensorySoftware.Shared.All.sln"
-
 if $GIT_CLEAN; then
 	title "Cleaning solution"
-	cd "${REPO_DIR}"
+	cd "${shared_repository_dir}"
 	git clean -fxd  || die 1 "== git clean failed =="
 	cd -
 fi
 
-if $RESTORE; then
-	title "Restoring solution packages"
-	nuget restore "${SOLUTION_PATH}" || die 1 "== package restore failed =="
-fi
+SOURCE_FOLDER="${shared_repository_dir}/Source"
 
-if $BUILD; then
-	title "Building solution"
-	dotnet build  "${SOLUTION_PATH}" --configuration=Debug --verbosity=quiet -consoleloggerparameters:ErrorsOnly || die 1  "== build failed =="
-fi
+title "Building shared desktop projects"
+
+echo ""
+echo "Shared:"
+dotnet build "${SOURCE_FOLDER}/SensorySoftware.Shared/SensorySoftware.Shared.csproj" --configuration Debug --verbosity quiet -consoleloggerparameters:ErrorsOnly || die 1  "== build failed =="
+
+echo ""
+echo "Shared.Desktop:"
+dotnet build "${SOURCE_FOLDER}/SensorySoftware.Shared.Desktop/SensorySoftware.Shared.Desktop.csproj" --configuration Debug --verbosity quiet -consoleloggerparameters:ErrorsOnly || die 1  "== build failed =="
+
+echo ""
+echo "Symbols.MetafileReader.Desktop:"
+dotnet build "${SOURCE_FOLDER}/SensorySoftware.Symbols.MetafileReader.Desktop/SensorySoftware.Symbols.MetafileReader.Desktop.csproj" --configuration Debug --verbosity quiet -consoleloggerparameters:ErrorsOnly || die 1  "== build failed =="
+
+echo ""
+echo "Shared.FluentUI:"
+dotnet build "${SOURCE_FOLDER}/SensorySoftware.Shared.FluentUI/SensorySoftware.Shared.FluentUI.csproj" --configuration Debug --verbosity quiet -consoleloggerparameters:ErrorsOnly || die 1  "== build failed =="
+
+echo ""
+echo "Shared.HardwareLicensingServiceClient:"
+dotnet build "${SOURCE_FOLDER}/SensorySoftware.Shared.HardwareLicensingServiceClient/SensorySoftware.Shared.HardwareLicensingServiceClient.csproj" --configuration Debug --verbosity quiet -consoleloggerparameters:ErrorsOnly || die 1  "== build failed =="
diff --git a/BAN-WORK-TOP/Scripts/application/pack/pack-eyegaze b/BAN-WORK-TOP/Scripts/application/pack/pack-eyegaze
--- a/BAN-WORK-TOP/Scripts/application/pack/pack-eyegaze
+++ b/BAN-WORK-TOP/Scripts/application/pack/pack-eyegaze
@@ -7,7 +7,7 @@
 #   eyegaze_repository_dir - absolute path to directory of the eyegaze repository
 #
 # Required scripts: 
-#   clear-eyegaze-cache
+#   clear-package-cache
 #
 # Optional scripts: 
 #   eyegaze - for pre-building
@@ -33,8 +33,8 @@ function echo_help() {
 
 EYEGAZE_PACKAGES_PROPS="${eyegaze_repository_dir}/Source/packages.props"
 SET_PACKAGE_VERSION=5.5.5
+DEFAULT_PACKAGE_VERSION=$(grep -oP "Version>\K${VERSION_REGEX}+" "${EYEGAZE_PACKAGES_PROPS}")
 VERSION_REGEX='[0-9]\.[0-9]\.[0-9]'
-CURRENT_PACKAGE_VERSION=$(grep -oP "Version>\K${VERSION_REGEX}+" "${EYEGAZE_PACKAGES_PROPS}")
 BUILD_BEFORE_PACKING=false
 SET_CONFIG=false
 
@@ -66,37 +66,35 @@ if $SET_CONFIG; then
   say "
   -- Setting EyeGaze Packages.Props Version --
   "
-  EYEGAZE_PACKAGES_PROPS="${eyegaze_repository_dir}/Source/packages.props"
   sed --in-place s_"Version>${VERSION_REGEX}\+"_"Version>${DEFAULT_PACKAGE_VERSION}"_g ${EYEGAZE_PACKAGES_PROPS}
   
-  say "Show version now in EYEGAZE packages.props: $CURRENT_PACKAGE_VERSION"
-  
+  say "Show version now in EYEGAZE packages.props: ${DEFAULT_PACKAGE_VERSION}"
 fi
 
 if $BUILD_BEFORE_PACKING; then
-  eyegaze -b || die 1 "Build failed"
+  eyegaze || die 1 "Build failed"
 fi
 
 say "
 -- Copying packages from output directory to local package store --
 "
 
-cp -v "${eyegaze_repository_dir}/Source/SensorySoftware.EyeGaze/bin/Debug/SensorySoftware.EyeGaze.${CURRENT_PACKAGE_VERSION}.nupkg" "${local_package_store}" || die 1 "Cannot copy a package that doesn't exist"
-cp -v "${eyegaze_repository_dir}/Source/SensorySoftware.EyeGaze.Desktop/bin/Debug/SensorySoftware.EyeGaze.Desktop.${CURRENT_PACKAGE_VERSION}.nupkg" "${local_package_store}" || die 1 "Cannot copy a package that doesn't exist"
+cp -v "${eyegaze_repository_dir}/Source/SensorySoftware.EyeGaze/bin/Debug/SensorySoftware.EyeGaze.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}" || die 1 "Cannot copy a package that doesn't exist"
+cp -v "${eyegaze_repository_dir}/Source/SensorySoftware.EyeGaze.Desktop/bin/Debug/SensorySoftware.EyeGaze.Desktop.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}" || die 1 "Cannot copy a package that doesn't exist"
 
 
 say "
 -- Removing cached packages from global nuget cache --
 "
 
-clear-eyegaze-cache
+clear-package-cache 'sensorysoftware.eyegaze' 'sensorysoftware.eyegaze.desktop'
 
 if $SET_CONFIG; then
   say "
   -- Setting Grid Directory.Build.Props EyeGazeVersion --
   "
   GRID_DIRECTORY_BUILD_PROPS="${grid_repository_dir}/Source/Directory.Build.props"
-  sed --in-place s_"EyeGazeVersion>${VERSION_REGEX}\+"_"EyeGazeVersion>${CURRENT_PACKAGE_VERSION}"_g ${GRID_DIRECTORY_BUILD_PROPS}
+  sed --in-place s_"EyeGazeVersion>${VERSION_REGEX}\+"_"EyeGazeVersion>${DEFAULT_PACKAGE_VERSION}"_g ${GRID_DIRECTORY_BUILD_PROPS}
   
   
   say "Show EyeGazeVersion now in GRID Directory.Build.props:"
diff --git a/BAN-WORK-TOP/Scripts/application/pack/pack-shared b/BAN-WORK-TOP/Scripts/application/pack/pack-shared
--- a/BAN-WORK-TOP/Scripts/application/pack/pack-shared
+++ b/BAN-WORK-TOP/Scripts/application/pack/pack-shared
@@ -7,7 +7,7 @@
 #   shared_repository_dir - absolute path to directory of the shared repository
 #
 # Required scripts: 
-#   clear-shared-cache
+#   clear-package-cache
 #
 # Optional scripts: 
 #   shared - for pre-building
@@ -26,13 +26,14 @@ function echo_help() {
     echo " "
     echo "actions:"
     echo "-h, --help             show brief help"
-    echo "-s, --set-config       set directory build props in both shared and Grid to ${DEFAULT_PACKAGE_VERSION}. Will also build"
+    echo "-s, --set-config       set directory build props in both shared and Grid to ${SET_PACKAGE_VERSION}. Will also build"
     echo "-b, --build            Build the shared solution"
     die 0
 }
 
-
-DEFAULT_PACKAGE_VERSION=2.0.0
+SHARED_DIRECTORY_BUILD_PROPS="${shared_repository_dir}/Source/Directory.Build.props"
+SET_PACKAGE_VERSION=5.5.5
+DEFAULT_PACKAGE_VERSION=$(grep -oP "Version>\K${VERSION_REGEX}+" "${SHARED_DIRECTORY_BUILD_PROPS}")
 VERSION_REGEX='[0-9]\.[0-9]\.[0-9]'
 BUILD_BEFORE_PACKING=false
 SET_CONFIG=false
@@ -44,9 +45,9 @@ while test $# -gt 0; do
       ;;
     -s|--set-config)
       SET_CONFIG=true
-      # It is nonsensical to set the config in Shared/Grid and not build in between.
+      # Run build process to ensure packages are built and copied before setting configs.
       BUILD_BEFORE_PACKING=true
-      DEFAULT_PACKAGE_VERSION=5.5.5
+      DEFAULT_PACKAGE_VERSION=${SET_PACKAGE_VERSION}
 
       shift
       ;;
@@ -62,38 +63,35 @@ while test $# -gt 0; do
 done
 
 if $SET_CONFIG; then
-  # Package version must be higher than the current version for Grids dependencies. For example, Grid depends on Eyegaze which depends on shared (as of 06/04/2022 this is roughly version 2.0.40.
+  # Package version must be higher than the current version for Grids dependencies. For example, Grid depends on Eyegaze which depends on shared (as of 06/04/2022 this is roughly version 2.0.40).
   # The version we choose needs to be higher than these dependencies.
   say "
   -- Setting Shared Directory.Build.Props Version --
   "
-  SHARED_DIRECTORY_BUILD_PROPS="${shared_repository_dir}/Source/Directory.Build.props"
   sed --in-place s_"Version>${VERSION_REGEX}\+"_"Version>${DEFAULT_PACKAGE_VERSION}"_g ${SHARED_DIRECTORY_BUILD_PROPS}
   
-  say "Show Shared Version now in Directory.Build.props:"
-  grep -oP "Version>${VERSION_REGEX}+" "${SHARED_DIRECTORY_BUILD_PROPS}"
-  
+  say "Show version now in SHARED Directory.Build.props: ${DEFAULT_PACKAGE_VERSION}"  
 fi
 
 if $BUILD_BEFORE_PACKING; then
-  shared -b || die 1 "Build failed"
+  shared || die 1 "Build failed"
 fi
 
 say "
 -- Copying packages from output directory to local package store --
 "
 
-cp -v "${shared_repository_dir}/Source/SensorySoftware.Shared/bin/Debug/SensorySoftware.Shared.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}"
-cp -v "${shared_repository_dir}/Source/SensorySoftware.Symbols.MetafileReader.Desktop/bin/Debug/SensorySoftware.Symbols.MetafileReader.Desktop.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}"
-cp -v "${shared_repository_dir}/Source/SensorySoftware.Shared.Desktop/bin/Debug/SensorySoftware.Shared.Desktop.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}"
-cp -v "${shared_repository_dir}/Source/SensorySoftware.Shared.FluentUI/bin/Debug/SensorySoftware.Shared.FluentUI.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}"
-cp -v "${shared_repository_dir}/Source/SensorySoftware.Shared.HardwareLicensingServiceClient/bin/Debug/SensorySoftware.Shared.HardwareLicensingServiceClient.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}"
+cp -v "${shared_repository_dir}/Source/SensorySoftware.Shared/bin/Debug/SensorySoftware.Shared.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}" || die 1 "Cannot copy a package that doesn't exist"
+cp -v "${shared_repository_dir}/Source/SensorySoftware.Symbols.MetafileReader.Desktop/bin/Debug/SensorySoftware.Symbols.MetafileReader.Desktop.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}" || die 1 "Cannot copy a package that doesn't exist"
+cp -v "${shared_repository_dir}/Source/SensorySoftware.Shared.Desktop/bin/Debug/SensorySoftware.Shared.Desktop.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}" || die 1 "Cannot copy a package that doesn't exist"
+cp -v "${shared_repository_dir}/Source/SensorySoftware.Shared.FluentUI/bin/Debug/SensorySoftware.Shared.FluentUI.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}" || die 1 "Cannot copy a package that doesn't exist"
+cp -v "${shared_repository_dir}/Source/SensorySoftware.Shared.HardwareLicensingServiceClient/bin/Debug/SensorySoftware.Shared.HardwareLicensingServiceClient.${DEFAULT_PACKAGE_VERSION}.nupkg" "${local_package_store}" || die 1 "Cannot copy a package that doesn't exist"
 
 say "
 -- Removing cached packages from global nuget cache --
 "
 
-clear-shared-cache
+clear-package-cache 'sensorysoftware.shared' 'sensorysoftware.shared.desktop' 'sensorysoftware.shared.hardwarelicensingserviceclient'  'sensorysoftware.symbols.metafilereader.desktop' 'sensorysoftware.shared.fluentui'
 
 if $SET_CONFIG; then
   say "
@@ -103,6 +101,6 @@ if $SET_CONFIG; then
   sed --in-place s_"SharedVersion>${VERSION_REGEX}\+"_"SharedVersion>${DEFAULT_PACKAGE_VERSION}"_g ${GRID_DIRECTORY_BUILD_PROPS}
   
   
-  say "Show Grid SharedVersion now in Directory.Build.props:"
-  grep -oP "SharedVersion>${VERSION_REGEX}+" "${GRID_DIRECTORY_BUILD_PROPS}"
+  say "Show SharedVersion now in GRID Directory.Build.props:"
+  grep SharedVersion ${GRID_DIRECTORY_BUILD_PROPS}
 fi
