Update packing scripts

diff --git a/BAN-WORK-TOP/Scripts/application/build/shared b/BAN-WORK-TOP/Scripts/application/build/shared
--- a/BAN-WORK-TOP/Scripts/application/build/shared
+++ b/BAN-WORK-TOP/Scripts/application/build/shared
@@ -99,5 +99,5 @@ fi
 
 if $BUILD; then
 	title "Building solution"
-	msbuild32 "${SOLUTION_PATH}" -p:Configuration=Debug -verbosity:q -consoleloggerparameters:ErrorsOnly || die 1  "== build failed =="
+	dotnet build  "${SOLUTION_PATH}" --configuration=Debug --verbosity=quiet -consoleloggerparameters:ErrorsOnly || die 1  "== build failed =="
 fi
